/** @type {import('xo').FlatXoConfig} */
const xoConfig = [
	{
		ignores: ['examples/**', 'dist/**', 'tsup.config.ts', 'vitest.config.ts'],
	},
	{
		react: true,
		rules: {
			'@typescript-eslint/no-explicit-any': 'error',
			'react/react-in-jsx-scope': 'off',
			'react/prop-types': 'off',
			// Disabled: XO's stylistic rules conflict with Ink JSX patterns
			'@stylistic/indent': 'off',
			'@stylistic/jsx-quotes': 'off',
			'@stylistic/operator-linebreak': 'off',
			'@stylistic/function-paren-newline': 'off',
			'@stylistic/no-trailing-spaces': 'off',
			'@stylistic/eol-last': 'off',
			'@stylistic/key-spacing': 'off',
			'@stylistic/jsx-tag-spacing': 'off',
			'react/jsx-closing-tag-location': 'off',
			'react/jsx-sort-props': 'off',
			'react/no-array-index-key': 'off',
			'capitalized-comments': 'off',
			'require-unicode-regexp': 'off',
			'unicorn/prefer-at': 'off',
			'@typescript-eslint/no-unnecessary-type-assertion': 'off',
			'@typescript-eslint/strict-void-return': 'off',
			'react/jsx-indent': 'off',
			'react/jsx-indent-props': 'off',
			'react/jsx-tag-spacing': 'off',
			'react/prefer-read-only-props': 'off',
			'react/boolean-prop-naming': 'off',
			'unicorn/no-hex-escape': 'off',
			'new-cap': 'off',
			'no-promise-executor-return': 'off',
			// Disabled: purely stylistic/opinionated rules that would force a
			// wholesale reformat of this pre-existing codebase. XO's bug-catching
			// rules (unused vars, react-hooks/exhaustive-deps, no-explicit-any, etc.)
			// stay on.
			'@stylistic/object-curly-spacing': 'off',
			'@stylistic/object-curly-newline': 'off',
			'@stylistic/indent-binary-ops': 'off',
			'@stylistic/arrow-parens': 'off',
			'@stylistic/padding-line-between-statements': 'off',
			'@stylistic/no-mixed-operators': 'off',
			curly: 'off',
			'arrow-body-style': 'off',
			'prefer-destructuring': 'off',
			'func-names': 'off',
			'max-params': 'off',
			complexity: 'off',
			'unicorn/prevent-abbreviations': 'off',
			'unicorn/better-regex': 'off',
			'unicorn/prefer-string-replace-all': 'off',
			'unicorn/switch-case-braces': 'off',
			'unicorn/catch-error-name': 'off',
			'unicorn/prefer-ternary': 'off',
			'unicorn/no-for-loop': 'off',
			'unicorn/no-new-array': 'off',
			'@typescript-eslint/naming-convention': 'off',
			'@typescript-eslint/consistent-type-definitions': 'off',
			'@typescript-eslint/no-restricted-types': 'off',
			'@typescript-eslint/no-unsafe-type-assertion': 'off',
			'@typescript-eslint/promise-function-async': 'off',
			'@typescript-eslint/switch-exhaustiveness-check': 'off',
			'@typescript-eslint/use-unknown-in-catch-callback-variable': 'off',
			'@typescript-eslint/no-unsafe-assignment': 'off',
			'react-hooks/refs': 'off',
			'react/jsx-no-leaked-render': 'off',
			'react/jsx-curly-brace-presence': 'off',
			'react/jsx-boolean-value': 'off',
			'import-x/order': 'off',
			'import-x/no-duplicates': 'off',
		},
	},
	{
		files: ['src/__tests__/**'],
		rules: {
			'no-control-regex': 'off',
			// The ANSI-stripping regex is built via RegExp to avoid embedding a
			// raw ESC control byte in a literal.
			'prefer-regex-literals': 'off',
			'unicorn/prefer-string-raw': 'off',
			'@typescript-eslint/no-floating-promises': 'off',
			'@typescript-eslint/no-unsafe-assignment': 'off',
			'@typescript-eslint/no-unsafe-call': 'off',
			'@typescript-eslint/no-unsafe-member-access': 'off',
			'@typescript-eslint/no-unsafe-return': 'off',
			'@typescript-eslint/no-unsafe-argument': 'off',
		},
	},
];

export default xoConfig;
